version: 0.2

phases:
  install:
    commands:
      - docker buildx create --use

  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 721176634889.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - docker buildx build --platform linux/amd64,linux/arm64 -t 721176634889.dkr.ecr.us-east-2.amazonaws.com/multiarch-demo:latest --push .
